---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.7"
generator:
  name: "NewRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.34.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "c7ddec0ff638a1cfd019004b18917468d209883d"
    sha: "c7ddec0"
  parameters:
    - "version": "0.1.0"
    - "group_id": "shboland"
    - "description": "Rug archive for personal rugs"
    - "owner": "shboland"

